name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:  # Allows manual triggers of this workflow

permissions:
  contents: write
  pages: write
  id-token: write
  
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Doxygen and BibTeX
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen sphinx texlive-bibtex-extra

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r docs/requirements.txt

      - name: Install PyTorch - Linux
        run: >
          wget https://download.pytorch.org/libtorch/cpu/libtorch-cxx11-abi-shared-with-deps-2.7.1%2Bcpu.zip -O libtorch.zip &&
          unzip libtorch.zip -d $HOME &&
          rm -f libtorch.zip

      - name: Configure CMake - Linux / GCC
        # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
        # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
        run: >
          cmake -B ./build
          -DIGANET_BUILD_DOCS=ON
          -DIGANET_BUILD_EXAMPLES=OFF
          -DIGANET_BUILD_PCH=OFF
          -DTorch_DIR=$HOME/libtorch/share/cmake/Torch
          -S ${{ github.workspace }}

      - name: Generate Documentation
        run: cmake --build ./build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./build/docs/doxygen/html

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
